haproxy:
  image: ianbytchek/haproxy
  volumes:
    - './haproxy:/etc/haproxy:ro'
    - './ssl:/etc/ssl/private:ro'
  links:
    - nginx
    - tracker
  ports:
    - '5000:80'
    - '5001:443'
nginx:
  image: smebberson/alpine-nginx
  volumes:
    - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    - './public:/var/www:ro'
  restart: always
tracker:
  build: .
  restart: always
