nginx:
  image: smebberson/alpine-nginx
  volumes:
    - './nginx/ssl:/etc/nginx/ssl:ro'
    - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
  links:
    - haproxy
  ports:
    - '5000:80'
    - '5001:443'
haproxy:
  image: ianbytchek/haproxy
  volumes:
    - './haproxy:/etc/haproxy:ro'
  links:
    - web
web:
  build: .
  restart: always
